[theme]
primaryColor = "#828F59"
backgroundColor = "#F4F3EF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3D4035"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
headless = true
