[theme]
primaryColor = "#828F59"
backgroundColor = "#FFFFCD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3D4230"
font = "sans serif"

[client]
toolbarMode = "viewer"
showSidebarNavigation = false

[server]
headless = true
